// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/labstack/echo/v4"
	"unjuk_keterampilan/app/databases"
	"unjuk_keterampilan/app/modules/notes"
	"unjuk_keterampilan/app/modules/notes/repositorys"
	repositorys2 "unjuk_keterampilan/app/modules/users/repositorys"
	"unjuk_keterampilan/app/routes"
)

// Injectors from wire.go:

func SetupApp() *echo.Echo {
	db := databases.NewConnection()
	noteRepository := repositorys.NewNoteRepository(db)
	userRepository := repositorys2.NewUserRepository(db)
	noteService := notes.NewNoteService(noteRepository, userRepository)
	noteHandler := notes.NewNoteHandler(noteService)
	echoEcho := routes.Routes(noteHandler)
	return echoEcho
}

// wire.go:

var setVariabel = wire.NewSet(repositorys.NewNoteRepository, wire.Bind(new(repositorys.NoteRepositoryImpl), new(*repositorys.NoteRepository)), repositorys2.NewUserRepository, wire.Bind(new(repositorys2.UserRepositoryImpl), new(*repositorys2.UserRepository)), notes.NewNoteService, wire.Bind(new(notes.NoteServiceImpl), new(*notes.NoteService)), notes.NewNoteHandler, wire.Bind(new(notes.NoteHandlerImpl), new(*notes.NoteHandler)))
